version: '3'
services:
  web:
    build: .
    ports:
      - "8080:5000"
    volumes:
      - .:/web-application
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    command: ["./wait-for-it.sh", "database:5432", "--", "python", "app.py"]

    
  database:
    image: postgres:latest 
    environment:
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: webappdb
