version: '3'
services:
  web:
    build: .
    ports:
      - "8080:5000"
    volumes:
      - .:/web-application
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    depends_on:
      - database
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: change%4090
      MYSQL_DATABASE: webappdata
